<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_LoginDataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0982185a-20d9-4c17-9874-90d4c81096c8</testSuiteGuid>
   <testCaseLink>
      <guid>11b61062-71f5-47fe-93c5-e7111f869d79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_SD_01_ValidLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e075fa12-7c8e-49d8-83e9-7afc1778d31d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e075fa12-7c8e-49d8-83e9-7afc1778d31d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b83caecc-0704-426e-917d-06e306b5edc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e075fa12-7c8e-49d8-83e9-7afc1778d31d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5ed810fb-d2fc-4481-bccb-3bba3fe6fce6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e075fa12-7c8e-49d8-83e9-7afc1778d31d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>5f00d918-98e5-4381-8a7b-59179e2eb82e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
